### ISSUE TITLE
Can't start all the services

### ISSUE THREAD

**Issue by chaima-ben-alaya** [Fiware/tutorials.IoT-Agent#10]
I encountered the following problem while trying to start the services

Orion is the context broker
IoT-Agent is configured for the UltraLight Protocol
Context-Provider acts as a series of dummy IoT Sensors over HTTP

Creating db-mongo         ... done
Creating context-provider ... done
Creating fiware-iot-agent ... 
Creating fiware-orion     ... error

ERROR: for fiware-orion  Cannot create container for service orion: Conflict. The container name "/fiware-orion" is already in use by container "3b4b8e6a67831f7Creating fiware-iot-agent ... error
e) that container to be able to reuse that name.

ERROR: for fiware-iot-agent  Cannot start service iot-agent: driver failed programming external connectivity on endpoint fiware-iot-agent (affe4af16b6c4204d9def853736c091fcb80cb4c2fae1ea6698006052b7ce8c6): Error starting userland proxy: listen tcp 0.0.0.0:4041: bind: address already in use

ERROR: for orion  Cannot create container for service orion: Conflict. The container name "/fiware-orion" is already in use by container "3b4b8e6a67831f7e3faea28297d6306814d846856fefa597a0e28f75445e8a15". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for iot-agent  Cannot start service iot-agent: driver failed programming external connectivity on endpoint fiware-iot-agent (affe4af16b6c4204d9def853736c091fcb80cb4c2fae1ea6698006052b7ce8c6): Error starting userland proxy: listen tcp 0.0.0.0:4041: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by jason-fox** [comment]
It looks like you have a [Dangling Container](https://stackoverflow.com/questions/31697828/docker-run-name-is-already-in-use-by-container)

The reason behind this is that you have instantiated the tutorial using:

```console
docker-compose up
```
Rather than using the bash script which tidies up any remaining containers.

```console
./services start
````

You can also manually delete the offending containers using something like:

```console
docker ps -a
docker rm <name_of_the_docker_container>
```
