### ISSUE TITLE
Redundant registrations after provisioning

### ISSUE THREAD

**Issue by hylowaker** [FIWARE/tutorials.IoT-Agent#20]
In **Enabling Context Broker Commands** part, the doc says registration process is required to invoke the command.
However, I found that the registration is automatically created during provisioning step.
After I provisioned `bell001` and `door001`, corresponding registrations also exist in the DB, and I was able to ring the bell and open the door without any additional requests. 

In short, '13 Request:' works without '12 Request:'

The only difference is that `providingApplication` is set to `http://iot-agent:4041` in auto-added one, while its value is `http://orion:1026/v1` in manually requested one.
(`expiration` and `description` is also different though)

**Comment by jason-fox** [comment]
Fixed - 4565c62  - redundant registrations removed.
