### ISSUE TITLE
Push and Polling commands

### ISSUE THREAD

**Issue by arturohu** [FIWARE/tutorials.IoT-Agent#35]
I am following the tutorial, but I have encountered with some problems with the commands. I am deploying the Scorpio NGSI-LD version of the tutorial.

As far as I know, the are two types of commands to configure something on an IoT Device:

- Push command: The IoT Agent calls the IoT device's public address to send the command.
- Polling command: The IoT Agent brings the command to the IoT device in the next iteration between the device and IoTAgent (MQTT Cmd topic subscription or HTTP Reponse after the next report).

I believe the tutorial follows the push command approach because the endpoint is defined during device provisioning. However, in a real-world scenario, an IoT device might not have a public IP address to receive configurations and should follow the polling command way.

Does the polling command work with IoTAgent-JSON or UL and the Scorpio Broker?

**Comment by jason-fox** [comment]
Yes, this tutorial is using a push command. If you want to discuss details of a specific IoT Agent it would be better to raise an issue for the [IoT Agent itself](https://github.com/telefonicaid/iotagent-ul/issues) since support will depend on the IoT Agent used.
